sudo: required
services:
  - docker

language: php

python:
  - 2.7

cache: false

env:
  global:
    - PRODUCT=php-tarantool

# multiple php version exclusion matrix
matrix:
  include:
    # # - env: OS=el     DIST=6
    # # - env: OS=el     DIST=7
    # - env: OS=fedora DIST=26
    # - env: OS=fedora DIST=27
    # # - env: OS=ubuntu DIST=trusty
    # - env: OS=ubuntu DIST=xenial
    # - env: OS=ubuntu DIST=artful
    # # - env: OS=ubuntu DIST=bionic
    # # - env: OS=debian DIST=wheezy
    # # - env: OS=debian DIST=jessie
    # - env: OS=debian DIST=stretch
    # - { env: TARGET=test, php: 7.0     }
    - { env: TARGET=test, php: 7.1     }
    - { env: TARGET=test, php: nightly }
  fast_finish: true
  allowed_failures:
    - OS=el     DIST=6
    - OS=el     DIST=7
    - OS=fedora DIST=26
    - OS=fedora DIST=27
    - OS=ubuntu DIST=trusty
    - OS=ubuntu DIST=xenial
    - OS=ubuntu DIST=artful
    - OS=ubuntu DIST=bionic
    - OS=debian DIST=wheezy
    - OS=debian DIST=jessie
    - OS=debian DIST=stretch

script:
  - make -f .travis.mk ${TARGET}

notifications:
  email: true
  irc: false
